### ISSUE TITLE
想問Term Project~

### ISSUE THREAD

**Issue by cxxizn** [peter0512lee/YZU-Programming-Lab-II#1]
學長你好 想請問你有沒有期末作業的檔案 要寫Pokemon的 能不能借參考個 plz~

**Comment by tracyoct** [comment]
> 學長你好 想請問你有沒有期末作業的檔案 要寫Pokemon的 能不能借參考個 plz~

**Comment by tracyoct** [comment]
> 學長你好 想請問你有沒有期末作業的檔案 要寫Pokemon的 能不能借參考個 plz~

**Comment by peter0512lee** [comment]
我沒有欸 可能每屆都不一樣 SORRY囉
